# Spring 数据源 (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///192.168.99.100:3306/test?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # Hibernate 属性，SQL 方言使得 Hibernate 为所选数据库生成更好的 SQL
        show_sql: true #Show or not log for each sql query
        format_sql: true  #格式化sql
        use_sql_comments: true #使SQL 语句中自动注入注释，增加可读性
        generate_statistics: false  #提供了Hibernate应用中操作的统计信息